### ISSUE TITLE
0.7.5 audio player Notification pause and close buttons do no work, only opens the app

### ISSUE THREAD

**Issue by Cormak** [theScrabi/NewPipe#200]
I have a feeling this is widespread, but I just upgraded to 0.7.5 and when using the audio playback feature, the audio player notification buttons do not work. It's as if there's no active buttons at all and tapping anywhere on the notification, even on the buttons, just brings up Newpipe.

This is on a Moto X 2015 Pure Edition.

**Comment by McCoy9000** [comment]
Same here but only in a Marshmallow device. In my other one running Kit-kat works just fine.

**Comment by wb9688** [comment]
Here it's running fine on Lollypop...
Op 21 feb. 2016 08:46 schreef "McCoy9000" <notifications@github.com>:

**Comment by theScrabi** [comment]
Yes well, I might now the error.

**Comment by theScrabi** [comment]
fixed.

**Comment by McCoy9000** [comment]
Sorry but you mean it will be fixed on next version? I still have the same issue.

**Comment by theScrabi** [comment]
Of course. If you download it from f-droid it will be fixed with the next version.
